### PR TITLE
FP-176 Mobile on click show control bar instead of pausing video

### PR DESCRIPTION
**Pull request by Ankit-Exads**

### CODE REVIEW

**Review by ZentoDH — COMMENTED** [review]
Nice work, just one thing. The double tap to skip 10 seconds doesn't work if the bar is hidden. When this is the case, it should just skip 10 seconds and not show the touchbar.

**Comment by Ankit-Exads** [comment]
Created a new ticket to investigate the above problem https://exogroup.atlassian.net/browse/FP-377

**Review by fpfcarvalho — APPROVED** [review]

**Review by ZentoDH — APPROVED** [review]

**Review by ZentoDH — APPROVED** [review]
Tested on real iPhone and android studio android emulator. Android was bugged on master and fixed now in the branch. LGTM

**Review by fpfcarvalho — APPROVED** [review]

**Comment by joewiey** [comment]
Update

Pada Kha, 14 Nov 2024, 7:37 PTG Bruno Pick ***@***.***>
menulis:

**Pull request merged**
