### PR TITLE
Version 3

### LINKED ISSUE #225: [Error] (204): Timeout error. Failed to play video.
Hi,
i have problem on IE/EDGE, source hls m3u8: [Error] (204): Timeout error. Failed to play video. 

On other browsers streaming is OK.

### LINKED ISSUE #251: Google fonts issue
is there any way to remove google fonts from fluid player?

this url https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css contains google fonts which makes the website very slow

### LINKED ISSUE #271: Not working on iOS
Hi,

I have an issue with the latest version of fluid player.
I included the player on our website. There is a preroll video (managed with a proper VAST xml file). But on iOS the player goes into infinite loading when I click on the play-button.
On Android smartphones it works nicely.
When I check firebug I get the following error code in the console: 
```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
(fluidplayer.min.js?ver=4.9.8:1)
```
Anybody who has an idea what the bugfix could be?
the URL for the website is [www.medienmanager.at](url)

Thanks a lot!
BR, George

### LINKED ISSUE #277: NPM repository
Is there a npm repository or how would I be able to add this via npm/yarn?

### LINKED ISSUE #314: DOM element
Could you support init the player from a dom-node? This would help us integrate fluid-player in a UI library.

E.g. this pseudo code:
```javascript
document.querySelectorAll( '[data-video]' ).forEach( function( video )
{
    fluidPlayer( video, ... );
})
```

Possible fix:
```javascript
var videoPlayer = typeof(idVideoPlayer) == 'string' ? document.getElementById(idVideoPlayer) : idVideoPlayer;
```

### LINKED ISSUE #351: React JS integration
Please! How can I integrate this with react JS?

Thanks in advance!

### LINKED ISSUE #373: Unknown property name "opactity"
opactity -> opacity

https://github.com/fluid-player/fluid-player/blob/8cf42e259ddae4485329018b99c2615ec1f2b653/fluidplayer.css#L902

### LINKED ISSUE #411: on timeupdate not work
I setup my player like this 

```
<script>
var myFluidPlayer = fluidPlayer("video",
    {
        layoutControls: {
            subtitlesEnabled: true,
            autoPlay: true,
        }
    });

    myFluidPlayer.on('timeupdate', function(currentTime, duration, isCurrentlyPlayingAd){
        console.log(currentTime);
        console.log(duration);
});
</script>
```

I get in console log

`[FP_ERROR] Event not recognised`

I forget to tell I want to get current time and duration fro  video using API, Ive managed to use on Playing event but still cant get current time and duration.

### LINKED ISSUE #416: Не могу отключить кнопку с субтитрами
Всем привет!
Не могу убрать субтитры https://prnt.sc/qq1d6a
Уже даже в настройках прописал, все равно не убирается иконка http://prntscr.com/qq1ddt
Скачал последнюю версию. Подскажите пожалуйста, как их убрать?

ENG:

Hi everyone,
I am not able to remve subtitles https://prnt.sc/qq1d6a
I did update the configuration, but the button remains nevertheless http://prntscr.com/qq1ddt
Using the latest version. Any ideas how to remove?

### LINKED ISSUE #423: Skip button doesn't appear
I'm trying to setup a linear vast (preroll) video. It works fine overall, but I can't manage to activate the (default) skip button. It just doesn't show up, not even with display:none. 
"#skip_button_" is just not there.

To find the error I even put a console.log() into the "addSkipButton" function (within fluidplayer.js) to see wether its called, but it isn't.

These are my options...

```layoutControls: 
	{
	autoPlay:           true,
	mute: 				true,
	keyboardControl: 	false,
	preload: 			true,
	primaryColor: "#28B8ED",
	controlBar: {
			autoHide: true, // Default false
			autoHideTimeout: 2, // Default 3
			animated: true // Default true
		}
	},
vastOptions: 
	{
		adText: 'Werbung',
		adList :	[{	roll: 'preRoll', vastTag: vast	}],
		skipButtonCaption: 'Wait [seconds] more second(s)',
		skipButtonClickCaption: 'Watch main video <span class="skip_button_icon"></span>'
	}
```

Due to the fact that the skip button is default, it should show up, right?
What am I doing wrong? o.O

### LINKED ISSUE #424: Will that be a Vue.js version ?
Will that be a Vue.js version ? Or a tutorial on how to integrate it ?

### LINKED ISSUE #431: fluid player can't play in mobile
My site use fluid player but it can't run in mobile.

It displays an error as "[Error] (204): Timeout error. Failed to play video."

### LINKED ISSUE #436: Subtitle list closing before being able to select anything
* Sporadically, was unable to select a subtitle language because the subtitle list would "hide" before I could select anything.
* Chrome (Win10).
* Happening on demo site: https://docs.fluidplayer.com/subtitles/ as well as my own development environment.

I fixed this myself like so:
        if (subtitleChangeList.style.display == 'none') {
            subtitleChangeList.style.display = 'block';
            var mouseOut = function (event) {
                //sourceChangeListContainer.removeEventListener('mouseleave', mouseOut);
                subtitleChangeList.removeEventListener('mouseleave', mouseOut);
                subtitleChangeList.style.display = 'none';
            };
            //sourceChangeListContainer.addEventListener('mouseleave', mouseOut);
            subtitleChangeList.addEventListener('mouseleave', mouseOut);
        } else {
            subtitleChangeList.style.display = 'none';
        }

Now behaves as expected.

### PR DESCRIPTION
**Pull request by Addvilz**
# Fluid Player version 3.0.0

This version is a major rewrite of Fluid Player. All major features are now split from the main player
logic. 

### Following has changed

- NPM package with with ready to use module, ready to be used with dynamic pages and SPAs.
- Webpack used for CDN distribution.
- All external dependencies have been removed from repository, NPM versions are used instead.
- External dependencies are loaded on first time use.
- Countless number of small bug fixes and improvements.
- Only documented public API is now exposed to end users.
- Player instance can be initialized using either player element id or `HTMLVideoElement` node reference.
- Controls are hidden by default and becomes visible if so configured in settings or defaults (no button flash).

### Breaking changes

- Fluid Player no longer exposes private APIs and player internals not documented to be used from outside the player object itself. Users who rely on these APIs should open an issue requesting a public API to such currently internalized features and APIs.
- CDN no longer publishes CSS as a separate file. CSS is now bundled with JavaScript distribution of the player.

Closes #251 
Closes #277 
Closes #373 
Closes #424 
Closes #436 
Closes #431 
Closes #225 
Closes #411 
Closes #416 
Closes #271
Closes #423 
Closes #314 
Closes #351

### CODE REVIEW

**Review by golikov — APPROVED** [review]

**Review by Herzog81 — COMMENTED** [review]
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<video id="video-id"><source src="video.mp4" type="video/mp4" />
<script>
    var myFP = fluidPlayer(
        'video-id',	{
	"layoutControls": {
		"controlBar": {
			"autoHideTimeout": 3,
			"animated": true,
			"autoHide": true
		},
		"htmlOnPauseBlock": {
			"html": null,
			"height": null,
			"width": null
		},
		"autoPlay": true,
		"mute": true,
		"allowTheatre": true,
		"playPauseAnimation": true,
		"playbackRateEnabled": true,
		"allowDownload": true,
		"playButtonShowing": true,
		"fillToContainer": false,
		"posterImage": ""
	},
	"vastOptions": {
		"adList": [],
		"adCTAText": false,
		"adCTATextPosition": ""
	}
}
</script>

**Comment by Linux534** [comment]
> # Fluid Player version 3.0.0
> 
> This version is a major rewrite of Fluid Player. All major features are now split from the main player
> logic. 
> 
> ### Following has changed
> 
> - NPM package with with ready to use module, ready to be used with dynamic pages and SPAs.
> - Webpack used for CDN distribution.
> - All external dependencies have been removed from repository, NPM versions are used instead.
> - External dependencies are loaded on first time use.
> - Countless number of small bug fixes and improvements.
> - Only documented public API is now exposed to end users.
> - Player instance can be initialized using either player element id or `HTMLVideoElement` node reference.
> - Controls are hidden by default and becomes visible if so configured in settings or defaults (no button flash).
> 
> ### Breaking changes
> 
> - Fluid Player no longer exposes private APIs and player internals not documented to be used from outside the player object itself. Users who rely on these APIs should open an issue requesting a public API to such currently internalized features and APIs.
> - CDN no longer publishes CSS as a separate file. CSS is now bundled with JavaScript distribution of the player.
> 
> Closes #251 
> Closes #277 
> Closes #373 
> Closes #424 
> Closes #436 
> Closes #431 
> Closes #225 
> Closes #411 
> Closes #416 
> Closes #271
> Closes #423 
> Closes #314 
> Closes #351

**Review by joker534 — APPROVED** [review]

**Comment by diaqad** [comment]
Hello
Is it possible to get code of the latest version for playing m3u8 link on blogs?
thank you in advance!

like this code:
<link href = "https://cdn.fluidplayer.com/v2/current/fluidplayer.min.css" rel = "stylesheet" type = "text / css"> </link>
<script src = "https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js"> </script>

<video id = "hls-video">
    <source src = "https://yourlink.m3u8" type = "application / x-mpegURL"> </source>
  
  
</video>

<script>
    var myFP = fluidPlayer (
        'hls-video',
        {
            layoutControls: {
  fillToContainer: true,
  primaryColor: "# 00AACC",
  posterImage: 'https://yourimage.jpg',
  autoPlay: true,
  playButtonShowing: true,
  playPauseAnimation: true,
  mute: false,
  logo: {
   imageUrl: '',
    position: 'top left',
   clickUrl: '',
   opacity: 1,
   mouseOverImageUrl: null,
   imageMargin: '2px',
   hideWithControls: false,
   showOverAds: true,
      keyboardControl: true,
  },
  htmlOnPauseBlock: {
   html: '',
   height: 90,
   width: 728
  },
  allowDownload: false,
  allowTheatre: true,
  playbackRateEnabled: false,
  controlBar: {
   autoHide: true,
   autoHideTimeout: 3,
   animated: true
  },
            },
            vastOptions: {
              vastTimeout: 1000,
              
        }
      }
    );
  
  
</script>
<script type = "text / javascript">
         fluidPlayer ('hls-video');
  fluidPlayer (idVideoPlayer [, options]);
      </script>

**Review by nigae — COMMENTED** [review]
player = fluidPlayer(target [, options]);

**Review by nigae — COMMENTED** [review]
<video id="example-player">
    <source src="video.mp4" type="video/mp4"/>
</video>


<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<script>
    // fluidPlayer method is global when CDN distribution is used.
    var player = fluidPlayer('example-player');
</script>

**Review by nigae — COMMENTED** [review]
<video id='my-video' controls style="width: 640px; height: 360px;">
    <source src='vid_1080p.mp4' title='1080p' type='video/mp4' />
    <source src='vid_720p.mp4' title='720p' type='video/mp4' />
    <source src='vid_480p.mp4' title='480p' type='video/mp4' />
</video>
[fluid-player-3.0.0.tar.gz](https://github.com/fluid-player/fluid-player/files/8403770/fluid-player-3.0.0.tar.gz)

**Comment by nigae** [comment]
<video id='my-video' controls style="width: 640px; height: 360px;">
    <source src='vid_1080p.mp4' title='1080p' type='video/mp4' />
    <source src='vid_720p.mp4' title='720p' type='video/mp4' />
    <source src='vid_480p.mp4' title='480p' type='video/mp4' />
</video>

**Comment by nigae** [comment]
<video id='my-video' controls style="width: 640px; height: 360px;">
    <source data-fluid-hd src='vid_1080p.mp4' title='1080p' type='video/mp4' />
    <source data-fluid-hd src='vid_720p.mp4' title='720p' type='video/mp4' />
    <source src='vid_480p.mp4' title='480p' type='video/mp4' />
</video>

**Review by nigae — COMMENTED** [review]
<video id='my-video' controls style="width: 640px; height: 360px;">
    <source src='vid_1080p.mp4' title='1080p' type='video/mp4' />
    <source src='vid_720p.mp4' title='720p' type='video/mp4' />
    <source src='vid_480p.mp4' title='480p' type='video/mp4' />
</video>

**Review by nigae — COMMENTED** [review]
<video id='my-video' controls style="width: 640px; height: 360px;">
    <source data-fluid-hd src='vid_1080p.mp4' title='1080p' type='video/mp4' />
    <source data-fluid-hd src='vid_720p.mp4' title='720p' type='video/mp4' />
    <source src='vid_480p.mp4' title='480p' type='video/mp4' />
</video>

**Comment by monanika91** [comment]
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<video id="video-id"><source src="video.mp4" type="video/mp4" />
<script>
    var myFP = fluidPlayer(
        'video-id',	{
	"layoutControls": {
		"controlBar": {
			"autoHideTimeout": 3,
			"animated": true,
			"autoHide": true
		},
		"htmlOnPauseBlock": {
			"html": null,
			"height": null,
			"width": null
		},
		"autoPlay": false,
		"mute": false,
		"allowTheatre": true,
		"playPauseAnimation": false,
		"playbackRateEnabled": false,
		"allowDownload": true,
		"playButtonShowing": false,
		"fillToContainer": false,
		"posterImage": ""
	},
	"vastOptions": {
		"adList": [],
		"adCTAText": false,
		"adCTATextPosition": ""
	}
});
</script>

**Review by Spacekowboy69tx69 — COMMENTED** [review]
Ready

**Comment by Jong026440** [comment]
Good

**Comment by Jong026440** [comment]
[](url)

**Comment by Jong026440** [comment]
](url)

**Comment by Jong026440** [comment]
Amazing
Screenshot_20240318_040632_com android chrome

**Comment by celticdruidas111111** [comment]
> <script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
> <video id="video-id"><source src="video.mp4" type="video/mp4" />
> <script>
>     var myFP = fluidPlayer(
>         'video-id',	{
> 	"layoutControls": {
> 		"controlBar": {
> 			"autoHideTimeout": 3,
> 			"animated": true,
> 			"autoHide": true
> 		},
> 		"htmlOnPauseBlock": {
> 			"html": null,
> 			"height": null,
> 			"width": null
> 		},
> 		"autoPlay": true,
> 		"mute": true,
> 		"allowTheatre": true,
> 		"playPauseAnimation": true,
> 		"playbackRateEnabled": true,
> 		"allowDownload": true,
> 		"playButtonShowing": true,
> 		"fillToContainer": false,
> 		"posterImage": ""
> 	},
> 	"vastOptions": {
> 		"adList": [],
> 		"adCTAText": false,
> 		"adCTATextPosition": ""
> 	}
> }
> </script>

**Comment by celticdruidas111111** [comment]
> player = fluidPlayer(target [, options]);

**Review by akonjet5 — COMMENTED** [review]
images/fluid_icons.svg

**Pull request merged**
