### PR TITLE
Add destroy function

### PR DESCRIPTION
**Pull request by Addvilz**
Add ability to unload Fluid Player somewhat gracefully. See #119

### CODE REVIEW

**Comment by Addvilz** [comment]
Note: whitespace edit's in diff due to some random loose whitespaces in the codebase :/

**Comment by golikov** [comment]
Looks good

**Comment by HomAfromPTZ** [comment]
destroy() method not working because player not defined inside "destroy" function:
Line 7157: `var container = document.getElementById('fluid_video_wrapper_' + player.videoPlayerId);`

**Comment by Addvilz** [comment]
@HomAfromPTZ if you don't mind creating a pull request, we could publish that fairly quickly.

**Comment by sunxiang520** [comment]
When  destroy() method  is executed, the scheduled task is not destroyed, but it is always running there and an error is reported.   Uncaught TypeError: Cannot read property 'clientWidth' of null
    at Object.checkIfVolumebarIsRendered (fluidplayer.js:4773)
    at initiateVolumebar (fluidplayer.js:4724)

**Pull request merged**
