### PR TITLE
Cannot read the properties of null (reading 'duration')

### PR DESCRIPTION
**Pull request by MariaAlmeidaMJ**

### CODE REVIEW

**Review by leroybm — APPROVED** [review]
LGTM

**Review by fpfcarvalho — APPROVED** [review]

**Review by InfernalGunner99 — COMMENTED** [review]
Appoval Granted

**Review by InfernalGunner99 — COMMENTED** [review]
Files changed

**Review by InfernalGunner99 — COMMENTED** [review]
src/modules/adsupport.js

**Review by InfernalGunner99 — COMMENTED** [review]
@MariaAlmeidaMJ

**Review by InfernalGunner99 — COMMENTED** [review]
S

**Pull request closed without merging**
